
kubectl create namespace production



apiVersion: v1
kind: Pod
metadata:
  labels:
    app: web 
  name: redcolor
  namespace: production
spec:
  containers:
  - image: mmumshad/simple-webapp-color
    name: red-container
    env:
    - name: color
      value: red
    ports:
    - containerPort: 8080
    
    
    
    
    
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: web 
  name: bluecolor
  namespace: production
spec:
  containers:
  - image: mmumshad/simple-webapp-color
    name: blue-container
    env:
    - name: color
      value: blue
    ports:
    - containerPort: 8080
    
    
    

apiVersion: v1
kind: Service
metadata:
  name: color-service
  namespace: production
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30008
    
    
